# https://mlflow.org

mlflow:
  _target_: lightning.pytorch.loggers.mlflow.MLFlowLogger
  experiment_name: "medficientsam_distillation"
  run_name: null
  tracking_uri: ${paths.log_dir}/mlflow/mlruns
  tags: null
  prefix: ''
  artifact_location: null
